name: VerifyIssue

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
  check_run:

jobs:
  verify_linked_issue:
    runs-on: ubuntu-latest
    name: PR has linked issues.
    steps:
      - name: Verify Linked Issue
        uses: Numih/act-verify-linked-issue@master
        env:
          GITHUB_TOKEN: ${{ secrets.NUMIH_GITHUB_TOKEN }}
